slavebase:
  image: mesosphere/mesos-slave:0.23.0-1.0.ubuntu1404
  privileged: true
  command: supervisord -n
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: "localdocker"
    MESOS_MASTER: "zk://zookeeper:2181/mesos"
    MESOS_LOG_DIR: "/var/log"
    MESOS_WORK_DIR: "/var/lib/mesos"
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /usr/local/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
