slavebase:
  image: breerly/mesos
  privileged: true
  command: supervisord -n
  environment:
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_HOSTNAME: "localdocker"
    MESOS_MASTER: "zk://zookeeper:2181/mesos"
    MESOS_LOG_DIR: "/var/log"
    MESOS_WORK_DIR: "/var/lib/mesos"
  # volumes:
  #   - /tmp/mesoswork:/tmp/mesoswork
  #   - /var/run/docker.sock:/var/run/docker.sock
  #   - /sys:/sys
  #   - /proc:/proc
  # --net=host \
  # -e MESOS_ISOLATOR=cgroups/cpu,cgroups/mem \


